spring:
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:${spring.application.name}.yml?refreshEnabled=true
  cloud:
    nacos:
      config:
        enabled: ${DAMAI_NACOS_CONFIG_ENABLED:true}
        import-check:
          enabled: true
        server-addr: ${DAMAI_NACOS_SERVER_ADDR:nacos-server:8848}
      discovery:
        enabled: ${DAMAI_NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${DAMAI_NACOS_REGISTER_ENABLED:true}
        server-addr: ${DAMAI_NACOS_SERVER_ADDR:nacos-server:8848}
  sql:
    init:
      mode: ${DAMAI_PROGRAM_SQL_INIT_MODE:never}
