CREATE TABLE IF NOT EXISTS d_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_number BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    program_item_picture VARCHAR(1024),
    user_id BIGINT NOT NULL,
    program_title VARCHAR(512),
    program_place VARCHAR(100),
    program_show_time DATETIME(6),
    program_permit_choose_seat TINYINT NOT NULL DEFAULT 0,
    distribution_mode VARCHAR(256),
    take_ticket_mode VARCHAR(256),
    order_price DECIMAL(10, 0) NOT NULL DEFAULT 0,
    pay_order_type INT,
    order_status INT NOT NULL DEFAULT 1,
    expire_time DATETIME(6) NOT NULL,
    create_order_time DATETIME(6) NOT NULL,
    cancel_order_time DATETIME(6),
    pay_order_time DATETIME(6),
    create_time DATETIME(6) NOT NULL,
    edit_time DATETIME(6) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_d_order_order_number UNIQUE (order_number),
    INDEX idx_d_order_user_id (user_id),
    INDEX idx_d_order_program_id (program_id),
    INDEX idx_d_order_status_expire_time (order_status, expire_time)
);

CREATE TABLE IF NOT EXISTS d_order_ticket_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_number BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    ticket_user_id BIGINT NOT NULL,
    seat_id BIGINT,
    seat_info VARCHAR(100),
    ticket_category_id BIGINT,
    order_price DECIMAL(10, 0) NOT NULL DEFAULT 0,
    pay_order_price DECIMAL(10, 0),
    pay_order_type INT,
    order_status INT NOT NULL DEFAULT 1,
    create_order_time DATETIME(6) NOT NULL,
    cancel_order_time DATETIME(6),
    pay_order_time DATETIME(6),
    create_time DATETIME(6) NOT NULL,
    edit_time DATETIME(6) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    INDEX idx_d_order_ticket_user_order_number (order_number),
    INDEX idx_d_order_ticket_user_user_id (user_id),
    INDEX idx_d_order_ticket_user_ticket_user_id (ticket_user_id),
    INDEX idx_d_order_ticket_user_create_order_time (create_order_time)
);

CREATE TABLE IF NOT EXISTS d_order_async_message (
    id BIGINT NOT NULL AUTO_INCREMENT,
    message_key VARCHAR(128) NOT NULL,
    order_number BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    topic VARCHAR(128) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    message_status INT NOT NULL DEFAULT 1,
    payload TEXT NOT NULL,
    last_error VARCHAR(1024),
    create_time DATETIME(6) NOT NULL,
    edit_time DATETIME(6) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_d_order_async_message_key UNIQUE (message_key),
    INDEX idx_d_order_async_message_order_number (order_number),
    INDEX idx_d_order_async_message_status (message_status, edit_time)
);
